include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FlymeMultitaskingPrefs

FlymeMultitaskingPrefs_FILES = FLMRootListController.m
FlymeMultitaskingPrefs_FRAMEWORKS = UIKit
FlymeMultitaskingPrefs_INSTALL_PATH = /Library/PreferenceBundles
FlymeMultitaskingPrefs_CFLAGS = -fobjc-arc -Wall -Wextra
FlymeMultitaskingPrefs_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
