include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FlymeMultitaskingPrefs

FlymeMultitaskingPrefs_FILES = FLMRootListController.m
FlymeMultitaskingPrefs_FRAMEWORKS = UIKit
FlymeMultitaskingPrefs_PRIVATE_FRAMEWORKS = Preferences
FlymeMultitaskingPrefs_INSTALL_PATH = /Library/PreferenceBundles
FlymeMultitaskingPrefs_CFLAGS = -fobjc-arc -Wall -Wextra

include $(THEOS_MAKE_PATH)/bundle.mk
