include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FlymeLandscapePrefs

FlymeLandscapePrefs_FILES = FLMLandscapeRootListController.m
FlymeLandscapePrefs_FRAMEWORKS = UIKit
FlymeLandscapePrefs_INSTALL_PATH = /Library/PreferenceBundles
FlymeLandscapePrefs_CFLAGS = -fobjc-arc -Wall -Wextra
FlymeLandscapePrefs_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
